
[nfs]
172.31.95.65 ansible_ssh_user='ec2-user'

[webservers]
172.31.95.160 ansible_ssh_user='ec2-user'
172.31.85.8 ansible_ssh_user='ec2-user'

[db]
172.31.89.228 ansible_ssh_user='ubuntu' 

[lb]
172.31.87.14 ansible_ssh_user='ubuntu'

[test]
172.31.28.232 ansible_ssh_user='ubuntu'