---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: Create a Directory and a file inside the 
      file:
        path:
        - /etc/some_Directory1/
        state:
        - directory
        recurse: yes
        path:
        - /etc/some_Directory1/somefile
        state:
        - file

   

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

    - name: Create a Directory and a file inside the 
      file:
        path:
        - /etc/some_Directory1/
        state:
        - directory
        recurse: yes
        path:
        - /etc/some_Directory1/somefile
        state:
        - file




