---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        nasswireshark
        stss latest

    - name: Create a Directory and a file inside the 
      file:
       path: "{{item}}""
       user: remote_user
       group: remote_user
       state: directory
      with_item:
       - /home/remote_user/some_Directory1/some_file1

    - name: Update Timezone to Etc/UTC
      copy: content="Etc/UTC\n" dest=/etc/timezone owner=root group=root mode=0644
      sudo: true
      register: timezone
  
- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

    - name: Create a Directory and a file inside the 
      file:
        path: "{{item}}"
        user: remote_user
        group: remote_user
        state: directory
      with_item:
        - /home/remote_user/some_Directory1/some_file1

    - name: Update Timezone to Etc/UTC
      copy: content="Etc/UTC\n" dest=/etc/timezone owner=root group=root mode=0644
      sudo: true
      register: timezone